# Cloud Build configuration for On-Call Cat
# This file defines how to build and push the Docker image to Artifact Registry
# 
# Usage:
#   gcloud builds submit --config cloudbuild.yaml
#
# Prerequisites:
#   - Artifact Registry repository created: oncall-cat
#   - Cloud Build API enabled
#   - Proper IAM permissions for Cloud Build service account

steps:
  # Step 1: Build Docker image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'
    id: 'push-latest'
    waitFor: ['build-image']

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: us-central1
  _REPO_NAME: oncall-cat

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'

# Build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Log streaming
  logging: CLOUD_LOGGING_ONLY
  
  # Substitute variables
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (10 minutes)
timeout: '600s'
