# Cloud Build configuration for On-Call Cat
# This file is a simple wrapper that delegates to the SDK-based build automation
#
# Triggered automatically on push to main branch via Cloud Build GitHub trigger
#
# Prerequisites:
#   - Node.js 20+ available in build environment
#   - Cloud Build trigger configured for GitHub repository
#   - Proper IAM permissions for Cloud Build service account
#   - Dependencies installed (handled in step 1)

steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--prefer-offline', '--no-audit']
    id: 'install-deps'

  # Step 2: Run SDK-based build and deploy
  - name: 'node:20'
    entrypoint: 'node'
    args: ['infrastructure/cloud-build-automation.mjs', 'deploy']
    id: 'build-and-deploy'
    waitFor: ['install-deps']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'

# Build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Log streaming
  logging: CLOUD_LOGGING_ONLY

# Build timeout (10 minutes)
timeout: '600s'
