# Cloud Build configuration for On-Call Cat
# Builds Docker image and creates Cloud Deploy release
#
# Triggered automatically on push to main branch via Cloud Build GitHub trigger

steps:
  # Step 1: Ensure placeholder channel-mappings.json exists
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        [ -f channel-mappings.json ] || echo '{"databases":[]}' > channel-mappings.json
    id: 'create-placeholder'

  # Step 2: Build Docker image with commit SHA and latest tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILD_TIME=$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'
      - '.'
    id: 'build-image'
    waitFor: ['create-placeholder']

  # Step 3: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app'
    id: 'push-images'
    waitFor: ['build-image']

  # Step 4: Install Node.js dependencies for SDK script
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--prefer-offline', '--no-audit']
    id: 'install-deps'
    waitFor: ['push-images']

  # Step 5: Create Cloud Deploy release using SDK
  - name: 'node:20'
    entrypoint: 'node'
    args: ['infrastructure/cloud-build-automation.mjs', 'create-release']
    id: 'create-release'
    waitFor: ['install-deps']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
      - 'REGION=${_REGION}'
      - 'IMAGE_TAG=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'oncall-cat'

# Images to register
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Build timeout (10 minutes)
timeout: '600s'
