# Cloud Build configuration for On-Call Cat
# This file defines how to build and deploy via Cloud Deploy
# 
# Triggered automatically on push to main branch
#
# Prerequisites:
#   - Artifact Registry repository created: oncall-cat
#   - Cloud Build API enabled
#   - Cloud Deploy API enabled
#   - Proper IAM permissions for Cloud Build service account

steps:
  # Step 1: Build Docker image with BUILD_TIME
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ensure placeholder channel-mappings.json exists if not provided (for Docker COPY)
        [ -f channel-mappings.json ] || echo '{"databases":[]}' > channel-mappings.json
        docker build \
          --build-arg BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest \
          .
    id: 'build-image'

  # Step 2: Push image with both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app'
    id: 'push-images'
    waitFor: ['build-image']

  # Step 3: Create Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-${SHORT_SHA}'
      - '--delivery-pipeline=${_PIPELINE_NAME}'
      - '--region=${_REGION}'
      - '--images=oncall-cat=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
      - '--skaffold-file=skaffold.yaml'
    id: 'create-release'
    waitFor: ['push-images']

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: us-central1
  _REPO_NAME: oncall-cat
  _PIPELINE_NAME: oncall-cat-pipeline

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'

# Build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Log streaming
  logging: CLOUD_LOGGING_ONLY
  
  # Substitute variables
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (10 minutes)
timeout: '600s'
