# Cloud Build configuration for On-Call Cat
# Builds Docker image and creates Cloud Deploy release
#
# Triggered automatically on push to main branch via Cloud Build GitHub trigger

steps:
  # Step 1: Ensure placeholder channel-mappings.json exists
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        [ -f channel-mappings.json ] || echo '{"databases":[]}' > channel-mappings.json
    id: 'create-placeholder'

  # Step 2: Build Docker image with commit SHA and latest tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILD_TIME=$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'
      - '.'
    id: 'build-image'
    waitFor: ['create-placeholder']

  # Step 3: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app'
    id: 'push-images'
    waitFor: ['build-image']

  # Step 4: Create Cloud Deploy release using gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create rel-${SHORT_SHA}-$(date +%s) \
          --delivery-pipeline=${_PIPELINE_NAME} \
          --region=${_REGION} \
          --project=${PROJECT_ID} \
          --skaffold-file=skaffold.yaml \
          --images=oncall-cat=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}
    id: 'create-release'
    waitFor: ['push-images']

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'oncall-cat'
  _PIPELINE_NAME: 'oncall-cat-pipeline'

# Images to register
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Build timeout (10 minutes)
timeout: '600s'
